service: aws-node-line-bot

provider:
  name: aws
  runtime: nodejs16.x
  profile: default
  region: ap-northeast-1
  stage: ${opt:stage, 'dev'}
  # Redisを使いたい場合
  # vpc:
  #   securityGroupIds:
  #     - sg-xxxx
  #   subnetIds:
  #     - subnet-xxxx
  #     - subnet-xxxx
  environment:

custom:
  prune:
    automatic: true
    number: 3

functions:
  line-bot:
    handler: handler.callback
    timeout: 30
    events:
      - http:
          path: callback
          method: post
          cors: true
      
plugins:
  - serverless-prune-plugin
