service: aws-node-line-bot

provider:
  name: aws
  runtime: nodejs16.x
  profile: default
  region: ap-northeast-1
  stage: ${opt:stage, 'dev'}
  environment:
    CHANNEL_ACCESS_TOKEN: [YOUR LINE CHANNEL_ACCESS_TOKEN]
    CHANNEL_SECRET: [YOUR LINE CHANNEL_SECRET]
    OPENAI_API_KEY: [YOUR OPENAI_API_KEY]
    REDIS_URL: [YOUR REDIS_URL]

custom:
  prune:
    automatic: true
    number: 3

functions:
  line-bot:
    handler: handler.callback
    timeout: 900
    events:
      - http:
          path: callback
          method: post
          cors: true
      
plugins:
  - serverless-prune-plugin
